alpha = 1

[palette] 
bg = "111111"
fg = "d9e6f2"
r0 = "000000"
r1 = "b87a7a"
r2 = "7ab87a"
r3 = "b8b87a"
r4 = "7a7ab8"
r5 = "b87ab8"
r6 = "7ab8b8"
r7 = "d9d9d9"
b0 = "262626"
b1 = "dbbdbd"
b2 = "bddbbd"  
b3 = "dbdbbd"
b4 = "bdbddb"
b5 = "dbbddb"
b6 = "bddbdb"
b7 = "ffffff" 
