# Auto-generated using compose2nix v0.3.1.
{ pkgs, lib, ... }:{
  
  virtualisation.oci-containers.containers."dozzle-dozzle" = {
    image = "amir20/dozzle:latest";
    volumes = [
      "/var/run/podman/podman.sock:/var/run/docker.sock:ro"
    ];
    ports = [
      "8080:8080/tcp"
    ];
    log-driver = "journald";
    extraOptions = [
      "--network-alias=dozzle"
      "--network=dozzle_default"
    ];
  };
  
  systemd.services."podman-dozzle-dozzle" = {
    serviceConfig = {
      Restart = lib.mkOverride 90 "no";
    };
    after = [
      "podman-network-dozzle_default.service"
    ];
    requires = [
      "podman-network-dozzle_default.service"
    ];
    partOf = [
      "podman-compose-dozzle-root.target"
    ];
    wantedBy = [
      "podman-compose-dozzle-root.target"
    ];
  };

  systemd.services."podman-network-dozzle_default" = {
    path = [ pkgs.podman ];
    serviceConfig = {
      Type = "oneshot";
      RemainAfterExit = true;
      ExecStop = "podman network rm -f dozzle_default";
    };
    script = ''
      podman network inspect dozzle_default || podman network create dozzle_default
    '';
    partOf = [ "podman-compose-dozzle-root.target" ];
    wantedBy = [ "podman-compose-dozzle-root.target" ];
  };

  systemd.targets."podman-compose-dozzle-root" = {
    unitConfig = {
      Description = "Root target generated by compose2nix.";
    };
    wantedBy = [ "multi-user.target" ];
  };
  
}
