#!/bin/sh

riverctl map normal Super Tab spawn 'riverctl keyboard-layout us'
riverctl map normal Super Backspace spawn 'riverctl keyboard-layout fr' 

riverctl map normal Super+Shift Return spawn foot
riverctl map normal Super R spawn fuzzel
riverctl map normal Super S spawn 'grim -g "$(slurp -w 0)" -c - | wl-copy -t image/png'
riverctl map normal Super+Shift S spawn 'grim -c - | wl-copy -t image/png'

riverctl map normal Super Q close
riverctl map normal Super+Shift E exit

riverctl map normal Super J focus-view next
riverctl map normal Super K focus-view previous

riverctl map normal Super+Shift J swap next
riverctl map normal Super+Shift K swap previous

riverctl map normal Super Period focus-output next
riverctl map normal Super Comma focus-output previous

riverctl map normal Super+Shift Period send-to-output next
riverctl map normal Super+Shift Comma send-to-output previous

riverctl map normal Super Return zoom

riverctl map normal Super H send-layout-cmd rivertile "main-ratio -0.05"
riverctl map normal Super L send-layout-cmd rivertile "main-ratio +0.05"

riverctl map normal Super+Shift H send-layout-cmd rivertile "main-count +1"
riverctl map normal Super+Shift L send-layout-cmd rivertile "main-count -1"

riverctl map normal Super+Alt H move left 100
riverctl map normal Super+Alt J move down 100
riverctl map normal Super+Alt K move up 100
riverctl map normal Super+Alt L move right 100

riverctl map normal Super+Alt+Control H snap left
riverctl map normal Super+Alt+Control J snap down
riverctl map normal Super+Alt+Control K snap up
riverctl map normal Super+Alt+Control L snap right

riverctl map normal Super+Alt+Shift H resize horizontal -100
riverctl map normal Super+Alt+Shift J resize vertical 100
riverctl map normal Super+Alt+Shift K resize vertical -100
riverctl map normal Super+Alt+Shift L resize horizontal 100

riverctl map-pointer normal Super BTN_LEFT move-view

riverctl map-pointer normal Super BTN_RIGHT resize-view

riverctl map-pointer normal Super BTN_MIDDLE toggle-float

for i in $(seq 1 9)
do
    tags=$((1 << ($i - 1)))

    riverctl map normal Super $i set-focused-tags $tags

    riverctl map normal Super+Shift $i set-view-tags $tags

    riverctl map normal Super+Control $i toggle-focused-tags $tags

    riverctl map normal Super+Shift+Control $i toggle-view-tags $tags
done

all_tags=$(((1 << 32) - 1))
riverctl map normal Super 0 set-focused-tags $all_tags
riverctl map normal Super+Shift 0 set-view-tags $all_tags

riverctl map normal Super Space toggle-float

riverctl map normal Super F toggle-fullscreen

riverctl map normal Super Up    send-layout-cmd rivertile "main-location top"
riverctl map normal Super Right send-layout-cmd rivertile "main-location right"
riverctl map normal Super Down  send-layout-cmd rivertile "main-location bottom"
riverctl map normal Super Left  send-layout-cmd rivertile "main-location left"

riverctl declare-mode passthrough

riverctl map normal Super F11 enter-mode passthrough

riverctl map passthrough Super F11 enter-mode normal

riverctl background-color 0x002b36
riverctl border-color-focused 0xffffff07
riverctl border-color-unfocused 0xffffff06

riverctl set-repeat 45 300

riverctl rule-add -app-id 'float*' -title 'foo' float
riverctl rule-add -app-id "bar" csd
riverctl rule-add -app-id "org.pwmt.zathura" ssd

riverctl default-layout rivertile
rivertile -view-padding 6 -outer-padding 6 &

exec $HOME/.config/river/modules/start
