WARNING_FLAGS="-Wno-error=format-truncation -Werror=lto-type-mismatch"
POLLY_FLAGS="-fplugin=LLVMPolly.so -mllvm=-polly -mllvm=-polly-vectorizer=stripmine -mllvm=-polly-omp-backend=LLVM -mllvm=-polly-parallel -mllvm=-polly-scheduling=dynamic"
COMMON_FLAGS="-march=native -O3 -pipe -flto=thin -ffat-lto-objects -fno-semantic-interposition -ffunction-sections -fdata-sections ${POLLY_FLAGS} ${WARNING_FLAGS}"

CFLAGS="${COMMON_FLAGS}"
CXXFLAGS="${COMMON_FLAGS}"
FCFLAGS="${COMMON_FLAGS}"
FFLAGS="${COMMON_FLAGS}"

LDFLAGS="-Wl,-O2,--as-needed,--hash-style=gnu,--gc-sections,--sort-common -flto=thin -fuse-ld=mold"

MAKEOPTS="-j12"

LC_ALL="en_US.UTF-8"

ACCEPT_KEYWORDS="~amd64"
ACCEPT_LICENSE="*"

USE="alsa dbus dist-kernel fontconfig harfbuzz icu jpeg lto modules-compress modules-sign \
  nls opengl openmp pgo pipewire png profile pulseaudio screencast svg threads vaapi vulkan wayland webp X zstd \
  -doc -emacs -kde -savedconfig -xfce"

CPU_FLAGS_X86="aes avx avx2 avx512 f16c fma3 mmx mmxext pclmul popcnt rdrand sha sse sse2 sse3 sse4_1 sse4_2 sse4a ssse3 vpclmulqdq"
VIDEO_CARDS="radeonsi"

FEATURES="candy clean-logs compressdebug dedupdebug fail-clean \
  nodoc noinfo notitles parallel-fetch parallel-install splitdebug split-elog split-log \
  -news -sandbox -pid-sandbox -usersandbox"

EMERGE_DEFAULT_OPTS="--verbose --keep-going"
PORTAGE_LOGDIR="/var/log/portage"
PORTAGE_TMPDIR="/tmp"

GENTOO_MIRRORS="https://mirror.reenigne.net/gentoo/ \
  https://172.83.105.10/gentoo/ \
  https://mirrors.mit.edu/gentoo-distfiles/"
